### ISSUE TITLE
Convert Custom Yolov5 Trained Model into CoreML format model

### ISSUE THREAD

**Issue by NaeemKhan333** [john-rocky/CoreML-YOLOv5#1]
@john-rocky Thank you very much for such nice work. I have trained the yolov5s model on my custom data. Now I want to integrate with the ios Swift app. For integration, I want to convert my yolov5s model into CoreML format. Can guide me through the process of conversion of yolov5s to coreML format. Thanks

**Comment by john-rocky** [comment]
Hi.

I referred to this repo for Yolov5 conversion.
https://github.com/dbsystel/yolov5-coreml-tools

Good luck.

2022年1月4日(火) 21:01 NaeemKhan333 ***@***.***>:
