### ISSUE TITLE
How to use my own custom YOLOv5s model

### ISSUE THREAD

**Issue by hsnawn** [john-rocky/CoreML-YOLOv5#2]
HI, great work!. I tested this with the default model and it worked perfectly fine for me. However, I want to use my own custom-trained YOLOv5 model. I converted my YOLOv5s model to CoreML using coremltools and then using this command: `xcrun coremlcompiler compile MyModel.mlmodel MyModel.mlmodelc` in terminal I converted `.mlmodel` file to `.mlmodelc`. The build is successful but the app crashes when I select any image with error:
`Thread 9: Fatal error: Model initialization failed`

Do I need to change anything else?

**Comment by john-rocky** [comment]
Hi.
If you want to use pre-compiled coreml model, you need .swift file.

Try this.

```
xcrun coremlcompiler compile pathToYourModel.mlmodel .
xcrun coremlcompiler generate pathToYourModel.mlmodel . --language Swift
```

Or, you can compile model on app.

```
 let model = try yolov5s(configuration: MLModelConfiguration()).model
```

Does this make sense?

**Comment by hsnawn** [comment]
Great. It worked after I generated the swift file. Thank you for your help.
