### ISSUE TITLE
How did you convert yolov5s.mlmodel to yolov5smlmodelc

### ISSUE THREAD

**Issue by NaeemKhan333** [john-rocky/CoreML-YOLOv5#3]
I converted using `xcrum corecompiler compile yolov5s.mlmodel yolov5s.mlmodelc` and replaced the file. But it crashes when I make detections.

**Comment by john-rocky** [comment]
Hi.
If you want to use pre-compiled coreml model, you need .swift file.

Try this.

```
xcrun coremlcompiler compile pathToYourModel.mlmodel .
xcrun coremlcompiler generate pathToYourModel.mlmodel . --language Swift
```

Or, you can compile model on app.

```
 let model = try yolov5s(configuration: MLModelConfiguration()).model
```

Does this make sense?

**Comment by NaeemKhan333** [comment]
Thank you! It worked.
